from dataclasses import dataclass

HTTP_INVALID_DATA = 400
HTTP_INVALID_AUTH_DATA = 401
HTTP_NO_PERMISSIONS = 403
HTTP_NOT_FOUND = 404
HTTP_DATA_CONFLICT = 409
HTTP_TEAPOT = 418
HTTP_NOT_FULL_DATA = 424
HTTP_INTERNAL_ERROR = 500
HTTP_OK = 200

MAX_LOG_DATA_LENGTH = 512

IMAGE_UID_GENERATE_LEN = 30
ORDER_SECRET_CODE_GENERATE_LEN = 6
MAX_ORDER_NUMBER = 999999
ORDER_NUMBER_SEED = 5901273812

ORDER_COST_PERCENT_TO_REFERRER_BONUSES = 0.10
ORDER_COST_PERCENT_TO_REFERRER_AHEAD_1_BONUSES = 0.08
# ORDER_COST_PERCENT_TO_REFERRER_AHEAD_2_BONUSES = 0.06
# ORDER_COST_PERCENT_TO_REFERRER_AHEAD_3_BONUSES = 0.04
# ORDER_COST_PERCENT_TO_REFERRER_AHEAD_4_BONUSES = 0.02

@dataclass
class OrderStatuses:
    created = 'created'
    paid = 'paid'
    prepared = 'prepared'
    delivered = 'delivered'
    cancelled = 'cancelled'
